s1 = input("Enter 1st string: ")
s2 = input("Enter 2nd string: ")

s3 = s1 + s2

print("concatinated string is:", s3)
print("lower", s3.lower())
print("upper", s3.upper())
print("title", s3.title())
print("swapcase", s3.swapcase())
print("capitalize", s3.capitalize())
print("casefold", s3.casefold())
print("center", s3.center(30))
print("count of a:", s3.count("a"))
print("endswith:", s3.endswith("a"))
print("find a:", s3.find("a"))
print("isalnum:", s3.isalnum())
print("isdigit:", s3.isdigit())
print("isnumeric:", s3.isnumeric())
print("isspace:", s3.isspace())
print("replace:", s3.replace("a", "@"))