print("df.join() vs pd.merge()")
print()
print("1. df.join()")
print("- Joins DataFrames mainly on the index.")
print("- Best when the key is already in the index or when aligning by index.")
print("- Can join multiple DataFrames at once.")
print()
print("2. pd.merge()")
print("- Joins DataFrames using one or more columns as keys.")
print("- More flexible for database-style joins such as inner, left, right, and outer.")
print("- Works even when the matching columns are not indexes.")
print()
print("Primary difference:")
print("- Use join() for index-based alignment.")
print("- Use merge() for column-based matching and more control over join type.")